#!/bin/bash

BUILD_CFG=$OPENSHIFT_REPO_DIR/config/victimsweb.build.env
VICTIMS_REPO=$OPENSHIFT_DATA_DIR/victims-web
VICTIMS_MODULE=$VICTIMS_REPO/src/victims_web
VICTIMS_LIB=$OPENSHIFT_REPO_DIR/libs/victims_web

source $BUILD_CFG

# Check if we need to reclone the repo
if [ -d "${VICTIMS_REPO}" ]; then
        ORIGINAL=$(cd $VICTIMS_REPO && git config remote.origin.url)
        if [ "$ORIGINAL" != "$VICTIMS_GIT_URL" ]; then
                VICTIMS_GIT_CLEAN=1
        fi
fi

# Clean the repo if required
if [ $VICTIMS_GIT_CLEAN -eq 1 ]; then
        echo "[lib] Deleting old checkout of victims-web"
        rm -rf $VICTIMS_REPO
fi

# Clone the repo if not already exists
if [ ! -d $VICTIMS_REPO ]; then
        echo "[lib] Cloning victims-web from $VICTIMS_GIT_URL"
        git clone $VICTIMS_GIT_URL $VICTIMS_REPO
fi

# Branching and updates
echo "[lib] Switching to branch $VICTIMS_GIT_BRANCH"
(cd $VICTIMS_REPO && git checkout $VICTIMS_GIT_BRANCH)
echo "[lib] Fetching any updates for victims-web"
(cd $VICTIMS_REPO && git pull --rebase origin $VICTIMS_GIT_BRANCH)
echo "[lib] Copying over victims-web contents to app repo"
ln -sf $VICTIMS_MODULE $VICTIMS_LIB

